
language: java
jdk: openjdk11
cache:
   directories:
     "$HOME/.m2/repository"
script:
  - mvn -U clean verify
before_deploy:
   - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
   - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  provider: script
  skip_cleanup: true
  script: mvn deploy -s ./settings.xml -U -DskipTests -Prelease
  on:
    branch: master
after_deploy:
   - cd scripts
   - ./deploy-p2.sh
addons:
    apt:
      packages:
        - libxml2-utils
branches:
  only:
  - master
