
language: java
jdk: oraclejdk8
cache:
   directories:
     "$HOME/.m2/repository"
install: false
script:
  - mvn clean verify
before_deploy:
   - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
   - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  provider: script
  skip_cleanup: true
  script: mvn deploy -s ./settings.xml -U -DskipTests -Prelease
  on:
    branch: test-branch
branches:
  only:
  - test-branch